// <auto-generated />
namespace MyDigitalMenu.Migrations.IdentityDataContext
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _20210825_mig : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_20210825_mig));
        
        string IMigrationMetadata.Id
        {
            get { return "202108251536124_20210825_mig"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
